# Use a specific Node.js version (v16.15.0) with Alpine for smaller image size
FROM node:16.15.0-alpine

# Set working directory
WORKDIR /app

# Copy only package.json and package-lock.json to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Expose the port your React app runs on
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
